import type { ExtractedPerson, PersonRole } from './types';

/** 用 hostname 后缀匹配（去掉 www. 后：host === 条目 或 host.endsWith('.' + 条目)） */
export const NEWS_HOSTS = [
  // 央媒 / 通讯社 / 机关报
  'xinhuanet.com',
  'news.cn',
  'people.com.cn',
  'people.cn',
  'cctv.com',
  'cctv.cn',
  'cnr.cn',
  'chinanews.com',
  'chinanews.com.cn',
  'chinanews.cn',
  'gmw.cn',
  'ce.cn',
  'huanqiu.com',
  'qstheory.cn',
  'studytimes.cn',
  'cntheory.com',
  'chinadaily.com.cn',
  'chinadaily.cn',
  'cankaoxiaoxi.com',
  'cyol.com',
  'youth.cn',
  'legaldaily.com.cn',
  'stdaily.com',
  'workercn.cn',
  'grrb.com.cn',
  'farmer.com.cn',
  'china.com.cn',
  'cri.cn',

  // 都市报 / 地方党报 / 市场化媒体
  'thepaper.cn',
  'jiemian.com',
  'guancha.cn',
  'caixin.com',
  'bjnews.com.cn',
  'infzm.com',
  'oeeee.com',
  'nandu.com',
  'southcn.com',
  'nfnews.com',
  'bjd.com.cn',
  'jfdaily.com',
  'shobserver.com',
  'whb.cn',
  'eastday.com',
  'dayoo.com',
  'ycwb.com',
  'yangtse.com',
  'cqnews.net',
  'dahe.cn',
  'rednet.cn',
  'hsw.cn',
  'xinmin.cn',
  'btime.com',

  // 门户新闻 / 资讯
  'news.163.com',
  'c.m.163.com',
  'news.sina.com.cn',
  'news.sina.cn',
  'k.sina.com.cn',
  'k.sina.cn',
  'news.qq.com',
  'new.qq.com',
  'inews.qq.com',
  'news.sohu.com',
  'sohu.com',
  'ifeng.com',
  'yidianzixun.com',
  'toutiao.com',
  'hao123.com',

  // 财经 / 科技媒体
  '36kr.com',
  'huxiu.com',
  'tmtpost.com',
  'yicai.com',
  '21jingji.com',
  'stcn.com',
  'cs.com.cn',
  'cnstock.com',
  'eeo.com.cn',
  'cb.com.cn',
  'cls.cn',
  'wallstreetcn.com',
  'caijing.com.cn',
  'nbd.com.cn',
];

export const HOST_ORG: Record<string, string> = {
  'xinhuanet.com': '新华社',
  'news.cn': '新华社',
  'people.com.cn': '人民日报',
  'people.cn': '人民日报',
  'cctv.com': '央视',
  'cctv.cn': '央视',
  'cnr.cn': '央广网',
  'chinanews.com': '中新社',
  'chinanews.com.cn': '中新社',
  'chinanews.cn': '中新社',
  'gmw.cn': '光明日报',
  'ce.cn': '经济日报',
  'huanqiu.com': '环球时报',
  'qstheory.cn': '求是',
  'studytimes.cn': '学习时报',
  'cntheory.com': '学习时报',
  'chinadaily.com.cn': '中国日报',
  'chinadaily.cn': '中国日报',
  'cankaoxiaoxi.com': '参考消息',
  'cyol.com': '中国青年报',
  'youth.cn': '中国青年报',
  'legaldaily.com.cn': '法治日报',
  'stdaily.com': '科技日报',
  'workercn.cn': '工人日报',
  'grrb.com.cn': '工人日报',
  'farmer.com.cn': '农民日报',
  'china.com.cn': '中国网',
  'cri.cn': '国际在线',
  'thepaper.cn': '澎湃新闻',
  'jiemian.com': '界面新闻',
  'guancha.cn': '观察者网',
  'caixin.com': '财新',
  'bjnews.com.cn': '新京报',
  'infzm.com': '南方周末',
  'oeeee.com': '南方都市报',
  'nandu.com': '南方都市报',
  'southcn.com': '南方日报',
  'nfnews.com': '南方日报',
  'bjd.com.cn': '北京日报',
  'jfdaily.com': '解放日报',
  'shobserver.com': '上观新闻',
  'whb.cn': '文汇报',
  'eastday.com': '东方网',
  'dayoo.com': '广州日报',
  'ycwb.com': '羊城晚报',
  'yangtse.com': '扬子晚报',
  'cqnews.net': '华龙网',
  'dahe.cn': '大河网',
  'rednet.cn': '红网',
  'hsw.cn': '华商报',
  'xinmin.cn': '新民晚报',
  'btime.com': '北京时间',
  'news.163.com': '网易新闻',
  'c.m.163.com': '网易新闻',
  'news.sina.com.cn': '新浪新闻',
  'news.sina.cn': '新浪新闻',
  'k.sina.com.cn': '新浪新闻',
  'k.sina.cn': '新浪新闻',
  'news.qq.com': '腾讯新闻',
  'new.qq.com': '腾讯新闻',
  'inews.qq.com': '腾讯新闻',
  'news.sohu.com': '搜狐新闻',
  'sohu.com': '搜狐新闻',
  'ifeng.com': '凤凰网',
  'yidianzixun.com': '一点资讯',
  'toutiao.com': '今日头条',
  'hao123.com': '好123',
  '36kr.com': '36氪',
  'huxiu.com': '虎嗅',
  'tmtpost.com': '钛媒体',
  'yicai.com': '第一财经',
  '21jingji.com': '21世纪经济报道',
  'stcn.com': '证券时报',
  'cs.com.cn': '中国证券报',
  'cnstock.com': '上海证券报',
  'eeo.com.cn': '经济观察报',
  'cb.com.cn': '中国经营报',
  'cls.cn': '财联社',
  'wallstreetcn.com': '华尔街见闻',
  'caijing.com.cn': '财经',
  'nbd.com.cn': '每日经济新闻',
};

export function isNewsHost(hostname: string): boolean {
  const host = hostname.replace(/^www\./, '').toLowerCase();
  return NEWS_HOSTS.some((h) => host === h || host.endsWith(`.${h}`));
}

export function orgHintForHost(hostname: string): string | undefined {
  const host = hostname.replace(/^www\./, '').toLowerCase();
  const hit = Object.keys(HOST_ORG).find((h) => host === h || host.endsWith(`.${h}`));
  return hit ? HOST_ORG[hit] : undefined;
}

export function personId(name: string, _role?: PersonRole): string {
  return name;
}

export function makePerson(
  name: string,
  role: PersonRole,
  rawText: string,
  orgHint?: string,
): ExtractedPerson {
  return { id: personId(name, role), name, role, rawText, orgHint };
}
